In [1]:
# TO DO: manually edit file name and file type

FILE_NAME = "Ethanol_Biorefineries.csv"
MIME_TYPE = "text/csv"

In [2]:
# TO DO: just run this code snippet. It'll output column names

import os
import pandas as pd
from ca_biositing.pipeline.utils.gdrive_to_pandas import gdrive_to_df
CREDENTIALS_PATH = "../../../../../../resources/prefect/credentials.json"
DATASET_FOLDER = "../temp_external_datasets/"
print(f"Extracting raw data from '{FILE_NAME}'...")

credentials_path = CREDENTIALS_PATH
dataset_folder = DATASET_FOLDER

raw_df = gdrive_to_df(FILE_NAME, MIME_TYPE, credentials_path, dataset_folder)

if raw_df is None:
    print("Failed to extract data. Aborting.")

print("Successfully extracted raw data.")
print(raw_df.columns)

Extracting raw data from 'Ethanol_Biorefineries.csv'...
Successfully extracted raw data.
Index(['NAME', 'CITY', 'STATE', 'ADDRESS', 'TYPE', 'CAPACITY_MGY',
       'PRODUCTION_MGY', 'CONSTR_EXP'],
      dtype='object')

In [3]:
# TO DO: [type later]

from ca_biositing.pipeline.utils.geo_utils import parse_addresses

address_df, geoid_df = parse_addresses(
        raw_df,
        merge_columns=["ADDRESS", "CITY", "STATE"],
        lat=None,
        long=None
    )

added_address_df = pd.concat([address_df, geoid_df], axis=1)

TypeError: parse_addresses() got an unexpected keyword argument 'api_key'

In [5]:
added_address_df

,closest_address_line_1,closest_address_line_2,closest_city,closest_county,closest_state,closest_postal_code,closest_latitude,closest_longitude,closest_geoid,closest_state_name,closest_state_fips,closest_county_name,closest_county_fips
0,38469 133rd Street,None,Aberdeen,Brown County,SD,57401,45.459047,-98.545046,46013,SD,46,Brown County,013
1,13238 East Aspen Road,None,Adams,Gage County,NE,68301-4103,40.485498,-96.547623,31067,NE,31,Gage County,067
2,2356 510th Street,None,Albert City,Buena Vista County,IA,50510,42.777740,-94.941916,19021,IA,19,Buena Vista County,021
3,15300 780th Avenue,None,Albert Lea,Freeborn County,MN,56007-7083,43.574463,-93.296499,27047,MN,27,Freeborn County,047
4,26250 B Drive North,None,Albion,Calhoun County,MI,49224-9530,42.257015,-84.788554,26025,MI,26,Calhoun County,025
...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,711 6th Avenue Southeast,None,Winnebago,Faribault County,MN,56098-1000,43.762338,-94.151427,27043,MN,27,Faribault County,043
209,53331 Minnesota 19,None,Winthrop,Sibley County,MN,55396,44.541579,-94.340453,27143,MN,27,Sibley County,143
210,7878 140th Road South,None,Wood River,Hall County,NE,68883,40.815733,-98.609533,31079,NE,31,Hall County,079
211,1414 Road O,None,York,York County,NE,68467-8236,40.895715,-97.542953,31185,NE,31,York County,185
212,38480 County Road H,None,Yuma,Yuma County,CO,80759-7856,40.122691,-102.676716,08125,CO,08,Yuma County,125

# Geocoder Module

In [4]:
# only run once
import gspread
from ca_biositing.pipeline.etl.extract.factory import create_extractor

GSHEET_NAME = "test sheet"
WORKSHEET_NAME = "test sheet"

extract = create_extractor(GSHEET_NAME, WORKSHEET_NAME)

# API: Get all values? (change later)
# Mask rows labeled pending and geocode for each of them
# Deal with duplicates
# Update status
# Deal with duplicates?
# Load to locationaddress and get id
# Update ID
# API: Update values

In [5]:
df = extract()

23:11:19.001 | INFO    | Task run 'extract_test sheet' - Extracting raw data from 'test sheet' in 'test sheet'...

DEBUG: gsheet_to_df called for test sheet / test sheet
DEBUG: Authenticating with C:\Users\Abigail\OneDrive\Documents\GitHub\ca-biositing\resources\prefect\credentials.json
DEBUG: Opening spreadsheet test sheet
DEBUG: Opening worksheet by name: test sheet
DEBUG: Fetching all values from worksheet
DEBUG: Successfully fetched 8 rows

23:11:21.214 | INFO    | Task run 'extract_test sheet' - Successfully extracted raw data from test sheet.

C:\Users\Abigail\OneDrive\Documents\GitHub\ca-biositing\.pixi\envs\default\Lib\logging\__init__.py:1946: UserWarning: Logger 'prefect.task_runs' attempted to send logs to the API without a flow run id. The API log handler can only send logs within flow run contexts unless the flow run id is manually provided. Set PREFECT_LOGGING_TO_API_WHEN_MISSING_FLOW=ignore to suppress this warning.
  self.logger.log(level, msg, *args, **kwargs)

23:11:21.224 | INFO    | Task run 'extract_test sheet' - Finished in state Completed()

In [6]:
df

,name,address,city,county,zip,state,latitude,longitude,status,closest_address_line_1,...,closest_state,closest_postal_code,closest_latitude,closest_longitude,closest_geoid,closest_state_name,closest_state_fips,closest_county_name,closest_county_fips,is_na
0,4 CORNER GROWERS LLC,"9051 AGUAS FRIAS RD, CHICO, 95928, CA, CHICO, ...",CHICO,Butte,95928,CA,39.6333364,-121.8654062,true,9051 Aguas Frias Road,...,CA,95928-9522,39.6333364,-121.8654062,06007,CA,06,Butte County,007,FALSE
1,A & R CUNHA FARMS INC,"5069 FRENCH PEOPLE, MEEP MORP, , , MEEP MORP, ...",MEEP MORP,beep,,,37.8737728,-122.2079590,pending,,...,,,0,0,00000,,,,,FALSE
2,ADRIAN RANCH,"26554 E. RIVER RD, ESCALON, 95320, CA, ESCALON...",ESCALON,San Joaquin,95320,CA,37.7573830,-120.9821665,pending,,...,,,,,,,,,,FALSE
3,ALMOND TREE HULLING CO,"23175 RD 16, CHOWCHILLA, 93610, CA, CHOWCHILLA...",CHOWCHILLA,Madera,93610,CA,37.0861803,-120.2565377,true,23175 Road 16,...,CA,93610-8704,37.0861803,-120.2565377,06039,CA,06,Madera County,039,FALSE
4,ALMOND ORCHARDS INC,"9409 TROXEL RD, CHICO, 95938, CA, CHICO, 95938...",CHICO,Butte,95938,CA,39.6478491,-121.8435109,true,9409 Troxel Road,...,CA,95928,39.6478491,-121.8435109,06007,CA,06,Butte County,007,FALSE
5,ANTONOWICH HULLING,"2656 HOUSE AVE, DURHAM, 95938, CA, DURHAM, 959...",DURHAM,Butte,95938,CA,39.6251999,-121.8117102,pending,,...,,,,,,,,,,FALSE
6,ASSOCIATED HULLING AND SHELLING LP,"4506 SAYLOR ROAD, DENAIR, 95316, CA, DENAIR, 9...",DENAIR,Stanislaus,95316,CA,37.5724303,-120.8151822,true,4506 Saylor Road,...,CA,95316-9534,37.5724303,-120.8151822,06099,CA,06,Stanislaus County,099,FALSE

In [7]:
from ca_biositing.pipeline.utils.geo_utils import parse_addresses
from dotenv import load_dotenv
import pandas as pd

df = df.astype({'latitude': float, 'longitude': float})

address_df, geoid_df = parse_addresses(
        df,
        merge_columns=["address", "city", "zip", "state"],
        lat="latitude",
        long="longitude",
    )

added_address_df = pd.concat([address_df, geoid_df], axis=1)
added_address_df

Siesta Valley Recreation Area park
Siesta Valley Recreation Area point_of_interest

,status,closest_address_line_1,closest_address_line_2,closest_city,closest_county,closest_state,closest_postal_code,closest_latitude,closest_longitude,closest_geoid,closest_state_name,closest_state_fips,closest_county_name,closest_county_fips
1,true,100 California Shakespeare Theater Way Siesta ...,None,Orinda,Contra Costa County,CA,94563,37.873279,-122.205821,06013,CA,06,Contra Costa County,013
2,true,26554 East River Road,None,Escalon,San Joaquin County,CA,95320-9652,37.757383,-120.982167,06077,CA,06,San Joaquin County,077
5,true,2656 House Avenue,None,Durham,Butte County,CA,95938-9763,39.625200,-121.811710,06007,CA,06,Butte County,007

In [8]:
gc = gspread.service_account(filename=CREDENTIALS_PATH)
sh = gc.open('test sheet')
worksheet = sh.worksheet("test sheet")
worksheet.update([df.columns.values.tolist()] + df.values.tolist())

{'spreadsheetId': '1uIReRKplM5cGLy-5FCOikhUuhKC6ZrLH2tGihAxo1is',
 'updatedRange': "'test sheet'!A1:W8",
 'updatedRows': 8,
 'updatedColumns': 23,
 'updatedCells': 184}